version: "3.1"

services:
  foodstock_db:
    image: postgres
    container_name: foodstock_db
    restart: always
    environment:
      POSTGRES_DB: foodstock
      POSTGRES_USER: local
      POSTGRES_PASSWORD: localPW
      POSTGRES_PORT: 51085
    ports:
      - 51085:5432
    volumes:
      - ./db_data:/var/lib/postgres/data
    command:
      - "postgres"
      - "-c"
      - "log-statement=all"
